# Generated by Django 2.1.1 on 2018-12-23 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrenthistory',
            name='back_date',
            field=models.DateField(default=datetime.datetime(2019, 1, 22, 13, 46, 39, 48986)),
        ),
    ]
